from ..database import Base
from .fundmeldungen import TblMeldungen
from .fundortbeschreibung import TblFundortBeschreibung
from .fundorte import TblFundorte
from .meldung_user import TblMeldungUser
from .aemter_koordinaten import TblAemterCoordinaten
from .users import TblUsers
from .alldata import TblAllData
from .feedback import TblFeedback
from .feedbackdetails import TblFeedbackDetails
