"""init

Revision ID: 79565b5a4f8a
Revises: 80060d82260d
Create Date: 2023-03-30 23:37:40.524325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79565b5a4f8a'
down_revision = '80060d82260d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
