"""init

Revision ID: 80060d82260d
Revises: df8d9ea3c100
Create Date: 2023-02-27 08:23:45.282411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80060d82260d'
down_revision = 'df8d9ea3c100'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
