insert into beschreibung (id, beschreibung) values ('1', 'Im Haus');
insert into beschreibung (id, beschreibung) values ('2', 'Im Garten');
insert into beschreibung (id, beschreibung) values ('3', 'Auf dem Balkon/auf der Terrasse');
insert into beschreibung (id, beschreibung) values ('4', 'Am Fenster/an der Hauswand');
insert into beschreibung (id, beschreibung) values ('5', 'Industriebrache');
insert into beschreibung (id, beschreibung) values ('6', 'Im Wald');
insert into beschreibung (id, beschreibung) values ('7', 'Wiese/Weide');
insert into beschreibung (id, beschreibung) values ('8', 'Heidelandschaft');
insert into beschreibung (id, beschreibung) values ('9', 'Straßengraben/Wegesrand/Ruderalflur');
insert into beschreibung (id, beschreibung) values ('10', 'Gewerbegebiet');
insert into beschreibung (id, beschreibung) values ('11', 'Im oder am Auto');
insert into beschreibung (id, beschreibung) values ('99', 'Anderer Fundort');
