insert into beschreibung (id, beschreibung) values (1,'am Haus');
insert into beschreibung (id, beschreibung) values (2,'am Swimmingpoolrand');
insert into beschreibung (id, beschreibung) values (3,'Wildblumenwiese in einem stadtnahen Gart');
insert into beschreibung (id, beschreibung) values (4,'in einer Sickergrube');
insert into beschreibung (id, beschreibung) values (5,'im Schuppen');
insert into beschreibung (id, beschreibung) values (6,'Sportgelände, SSC Storkower Sport Club e');
insert into beschreibung (id, beschreibung) values (7,'vom Naturschutzfond Brandenburg betreute');
insert into beschreibung (id, beschreibung) values (8,'nach den Koordinaten im offenen Wald, in');
insert into beschreibung (id, beschreibung) values (9,'Balkon 2. OG');
insert into beschreibung (id, beschreibung) values (10,'beim Rasen mäen');
insert into beschreibung (id, beschreibung) values (11,'Vorgarten');
insert into beschreibung (id, beschreibung) values (12,'Fenster am Amazonia');
insert into beschreibung (id, beschreibung) values (13,'Waldrand (Lehmweg)');
insert into beschreibung (id, beschreibung) values (14,'Schrebergarten');
insert into beschreibung (id, beschreibung) values (15,'an einem Schaukasten in der Spreegalerie');
insert into beschreibung (id, beschreibung) values (16,'Hauswand');
insert into beschreibung (id, beschreibung) values (17,'Veranda');
insert into beschreibung (id, beschreibung) values (18,'Waldlichtung');
insert into beschreibung (id, beschreibung) values (19,'Garten');
insert into beschreibung (id, beschreibung) values (20,'in einem Betrieb');
insert into beschreibung (id, beschreibung) values (21,'Wegrand');
insert into beschreibung (id, beschreibung) values (22,'auf dem Hof');
insert into beschreibung (id, beschreibung) values (23,'Wiese');
insert into beschreibung (id, beschreibung) values (24,'am Rolladen');
insert into beschreibung (id, beschreibung) values (25,'Gewerbegebiet');
insert into beschreibung (id, beschreibung) values (26,'in der Wohnung');
insert into beschreibung (id, beschreibung) values (27,'Balkon 4. Etage');
insert into beschreibung (id, beschreibung) values (28,'Fahrradladen');
insert into beschreibung (id, beschreibung) values (29,'vor dem Fereinhaus');
insert into beschreibung (id, beschreibung) values (30,'Waldrand/ Heidelandschaft');
insert into beschreibung (id, beschreibung) values (31,'Heide');
insert into beschreibung (id, beschreibung) values (32,'Terrasse');
insert into beschreibung (id, beschreibung) values (33,'im Garten');
insert into beschreibung (id, beschreibung) values (34,'Balkon im 5. Stock');
insert into beschreibung (id, beschreibung) values (35,'Fensterbank');
insert into beschreibung (id, beschreibung) values (36,'am Haue');
insert into beschreibung (id, beschreibung) values (37,'im Gras vor der alten Chirurgie');
insert into beschreibung (id, beschreibung) values (38,'Straße vor dem Haus');
insert into beschreibung (id, beschreibung) values (39,'im Garteb');
insert into beschreibung (id, beschreibung) values (40,'ungemähte Wiese');
insert into beschreibung (id, beschreibung) values (41,'an Flugzeug in Technikhalle');
insert into beschreibung (id, beschreibung) values (42,'Pferdetränke');
insert into beschreibung (id, beschreibung) values (43,'Arndt-Gymnasium, Schulhof');
insert into beschreibung (id, beschreibung) values (44,'auf einem Heide bewachsenen Sandweg zwis');
insert into beschreibung (id, beschreibung) values (45,'in Bürogebäude');
insert into beschreibung (id, beschreibung) values (46,'Garten, Thuja-Hecke');
insert into beschreibung (id, beschreibung) values (47,'Baustoffhandel Balzke');
insert into beschreibung (id, beschreibung) values (48,'Habitats-/Fundbemerkung');
insert into beschreibung (id, beschreibung) values (49,'an Hauswand');
insert into beschreibung (id, beschreibung) values (50,'Betriebsgelände');
insert into beschreibung (id, beschreibung) values (51,'Niederlausitzer Heidelandschaft');
insert into beschreibung (id, beschreibung) values (52,'das Tier stieg Zossener Straße Ecke Bahn');
insert into beschreibung (id, beschreibung) values (53,'an Türrahmen eines Einfamilienhauses');
insert into beschreibung (id, beschreibung) values (54,'Am Marktplatz, drei Häuser neben dem Rat');
insert into beschreibung (id, beschreibung) values (55,'Auf Auto');
insert into beschreibung (id, beschreibung) values (56,'auf einem Grundstück neben den Bahngleis');
insert into beschreibung (id, beschreibung) values (57,'Hort Kinderinsel');
insert into beschreibung (id, beschreibung) values (58,'Kleingartenanlage');
insert into beschreibung (id, beschreibung) values (59,'unbewirtschafteten Wiese');
insert into beschreibung (id, beschreibung) values (60,'renaturierte Tagebaufläche');
insert into beschreibung (id, beschreibung) values (61,'im Grünstreifen am Radweg zwischen Sport');
insert into beschreibung (id, beschreibung) values (62,'im Vorgarten');
insert into beschreibung (id, beschreibung) values (63,'Ootheken an Gleisschotter oder Holzteile');
insert into beschreibung (id, beschreibung) values (64,'Autohaus');
insert into beschreibung (id, beschreibung) values (65,'extensiv genutzte Wiese');
insert into beschreibung (id, beschreibung) values (66,'vor der Eingangstür');
insert into beschreibung (id, beschreibung) values (67,'Naturgarten');
insert into beschreibung (id, beschreibung) values (68,'Hof');
insert into beschreibung (id, beschreibung) values (69,'Grundstück, Hundenapf');
insert into beschreibung (id, beschreibung) values (70,'Einkaufszentrums „Zentrum Schöneweide“ a');
insert into beschreibung (id, beschreibung) values (71,'am Haus (Wand am Laden)');
insert into beschreibung (id, beschreibung) values (72,'vor dem Haus');
insert into beschreibung (id, beschreibung) values (73,'im Haus');
insert into beschreibung (id, beschreibung) values (74,'am Fenster');
insert into beschreibung (id, beschreibung) values (75,'Wartungshalle');
insert into beschreibung (id, beschreibung) values (76,'Hauseingangstür');
insert into beschreibung (id, beschreibung) values (77,'Wildwiese 50 m vom Garten entfernt');
insert into beschreibung (id, beschreibung) values (78,'Kinderzimmer');
insert into beschreibung (id, beschreibung) values (79,'Festivalcamping, im Zelt');
insert into beschreibung (id, beschreibung) values (80,'NISSAN Service Center, am/ im Haus');
insert into beschreibung (id, beschreibung) values (81,'Innenraum');
insert into beschreibung (id, beschreibung) values (82,'Trockenfläche, Ackerland an der Nuthe');
insert into beschreibung (id, beschreibung) values (83,'auf dem Balkon');
insert into beschreibung (id, beschreibung) values (84,'auf Terrasse');
insert into beschreibung (id, beschreibung) values (85,'Büro');
insert into beschreibung (id, beschreibung) values (86,'Motorhaube');
insert into beschreibung (id, beschreibung) values (87,'im Swimmingpool');
insert into beschreibung (id, beschreibung) values (88,'Kiesgrube');
insert into beschreibung (id, beschreibung) values (89,'direkt an den Bahnschienen');
insert into beschreibung (id, beschreibung) values (90,'einem Freisitz am Wohnhaus in einer klei');
insert into beschreibung (id, beschreibung) values (91,'Ladengeschäft');
insert into beschreibung (id, beschreibung) values (92,'am Haus am Waldrand');
insert into beschreibung (id, beschreibung) values (93,'an einer Wand in der Tiefgarage eines Ne');
insert into beschreibung (id, beschreibung) values (94,'Pferdeweide');
insert into beschreibung (id, beschreibung) values (95,'Lichtung am Wald, direkt am Feldrand');
insert into beschreibung (id, beschreibung) values (96,'Hundewiese');
insert into beschreibung (id, beschreibung) values (97,'Bolzplatz');
insert into beschreibung (id, beschreibung) values (98,'Lichtfang');
insert into beschreibung (id, beschreibung) values (99,'in einem Lebensbaum auf dem Hof');
insert into beschreibung (id, beschreibung) values (100,'Lehrerzimmer');
insert into beschreibung (id, beschreibung) values (101,'Bioland Gemüsebaubetrieb (Gärtnerhof Kus');
insert into beschreibung (id, beschreibung) values (102,'Parkplatz unweit der A8');
insert into beschreibung (id, beschreibung) values (103,'an einer Tür');
insert into beschreibung (id, beschreibung) values (104,'im Büro');
insert into beschreibung (id, beschreibung) values (105,'Waldrand');
insert into beschreibung (id, beschreibung) values (106,'meine "Insektenwiese"');
insert into beschreibung (id, beschreibung) values (107,'Balkon');
insert into beschreibung (id, beschreibung) values (108,'Spielplatz neben dem Haus');
insert into beschreibung (id, beschreibung) values (109,'Mitten im Kiefernhochwald');
