"""Define initial  database structure.

Revision ID: 09020629e539
Revises:
Create Date: 2025-02-23 20:34:59.652603


Constraint names are pinned to the PostgreSQL defaults this migration
originally produced, so fresh databases match existing ones now that the
model MetaData carries a naming_convention (which would otherwise rename
unnamed constraints here retroactively).
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "09020629e539"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aemter",
        sa.Column("ags", sa.Integer(), nullable=False),
        sa.Column("gen", sa.String(length=100), nullable=False),
        sa.Column(
            "properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("ags", name="aemter_pkey"),
    )
    op.create_table(
        "beschreibung",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beschreibung", sa.String(length=45), nullable=False),
        sa.PrimaryKeyConstraint("id", name="beschreibung_pkey"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("user_name", sa.String(length=45), nullable=False),
        sa.Column("user_rolle", sa.String(length=1), nullable=False),
        sa.Column("user_kontakt", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_table(
        "fundorte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plz", sa.Integer(), nullable=False),
        sa.Column("ort", sa.String(), nullable=False),
        sa.Column("strasse", sa.String(length=100), nullable=False),
        sa.Column("kreis", sa.String(), nullable=False),
        sa.Column("land", sa.String(length=50), nullable=False),
        sa.Column("amt", sa.String(length=50), nullable=True),
        sa.Column("mtb", sa.String(length=50), nullable=True),
        sa.Column("beschreibung", sa.Integer(), nullable=False),
        sa.Column("longitude", sa.VARCHAR(length=25), nullable=False),
        sa.Column("latitude", sa.VARCHAR(length=25), nullable=False),
        sa.Column("ablage", sa.VARCHAR(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["beschreibung"],
            ["beschreibung.id"],
            name="fundorte_beschreibung_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="fundorte_pkey"),
    )
    op.create_table(
        "meldungen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("dat_fund_von", sa.Date(), nullable=False),
        sa.Column("dat_fund_bis", sa.Date(), nullable=True),
        sa.Column("dat_meld", sa.Date(), nullable=True),
        sa.Column("dat_bear", sa.Date(), nullable=True),
        sa.Column("bearb_id", sa.String(length=40), nullable=True),
        sa.Column("tiere", sa.Integer(), nullable=True),
        sa.Column("art_m", sa.Integer(), nullable=True),
        sa.Column("art_w", sa.Integer(), nullable=True),
        sa.Column("art_n", sa.Integer(), nullable=True),
        sa.Column("art_o", sa.Integer(), nullable=True),
        sa.Column("art_f", sa.Integer(), nullable=True),
        sa.Column("fo_zuordnung", sa.Integer(), nullable=True),
        sa.Column("fo_quelle", sa.String(length=1), nullable=True),
        sa.Column("fo_beleg", sa.String(length=1), nullable=True),
        sa.Column("anm_melder", sa.String(length=500), nullable=True),
        sa.Column("anm_bearbeiter", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["fo_zuordnung"],
            ["fundorte.id"],
            name="meldungen_fo_zuordnung_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="meldungen_pkey"),
    )
    op.create_table(
        "melduser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_meldung", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_finder", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_finder"],
            ["users.id"],
            name="melduser_id_finder_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["id_meldung"],
            ["meldungen.id"],
            name="melduser_id_meldung_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
            name="melduser_id_user_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="melduser_pkey"),
    )
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("melduser")
    op.drop_table("meldungen")
    op.drop_table("fundorte")
    op.drop_table("users")
    op.drop_table("beschreibung")
    #    op.drop_table('all_data_view')
    op.drop_table("aemter")
    # ### end Alembic commands ###
