"""implement feedback table

Revision ID: 1aa77659662a
Revises: 09020629e539
Create Date: 2025-04-13 20:40:12.940173


Constraint names are pinned to the PostgreSQL defaults this migration
originally produced (see 09020629e539 for rationale).
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1aa77659662a"
down_revision = "09020629e539"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name="feedback_types_pkey"),
        sa.UniqueConstraint("name", name="feedback_types_name_key"),
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feedback_type_id", sa.Integer(), nullable=False),
        sa.Column("source_detail", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["feedback_type_id"],
            ["feedback_types.id"],
            name="user_feedback_feedback_type_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_feedback_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="user_feedback_pkey"),
        sa.UniqueConstraint("user_id", name="user_feedback_user_id_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_feedback")
    op.drop_table("feedback_types")
    # ### end Alembic commands ###
