"""add geo_names table and fundorte grade columns

Revision ID: 7e9e54853fa2
Revises: a4d8f2b6c573
Create Date: 2026-06-16 20:59:37.972158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e9e54853fa2'
down_revision = 'a4d8f2b6c573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('ags', sa.BigInteger(), nullable=True),
    sa.Column('kreis', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_names'))
    )
    with op.batch_alter_table('geo_names', schema=None) as batch_op:
        batch_op.create_index('ix_geo_names_name_norm', ['name_norm'], unique=False)

    with op.batch_alter_table('fundorte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geo_grade', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('geo_confidence', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('geo_matched_level', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('geo_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('geo_graded_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundorte', schema=None) as batch_op:
        batch_op.drop_column('geo_graded_at')
        batch_op.drop_column('geo_reasons')
        batch_op.drop_column('geo_matched_level')
        batch_op.drop_column('geo_confidence')
        batch_op.drop_column('geo_grade')

    with op.batch_alter_table('geo_names', schema=None) as batch_op:
        batch_op.drop_index('ix_geo_names_name_norm')

    op.drop_table('geo_names')
    # ### end Alembic commands ###
