"""Add performance indexes for query optimization

Revision ID: b426f6a748b3
Revises: 8f660094eea7
Create Date: 2026-01-13 21:41:21.805325

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b426f6a748b3'
down_revision = '8f660094eea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundorte', schema=None) as batch_op:
        batch_op.create_index('ix_fundorte_amt_pattern', ['amt'], unique=False, postgresql_ops={'amt': 'varchar_pattern_ops'})

    with op.batch_alter_table('meldungen', schema=None) as batch_op:
        batch_op.create_index('ix_meldungen_dat_fund_von', ['dat_fund_von'], unique=False)
        batch_op.create_index('ix_meldungen_dat_meld', ['dat_meld'], unique=False)
        batch_op.create_index('ix_meldungen_fo_zuordnung', ['fo_zuordnung'], unique=False)
        batch_op.create_index('ix_meldungen_status_dat_fund_von', ['status', 'dat_fund_von'], unique=False)

    with op.batch_alter_table('melduser', schema=None) as batch_op:
        batch_op.create_index('ix_melduser_id_meldung_id_user', ['id_meldung', 'id_user'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))

    with op.batch_alter_table('melduser', schema=None) as batch_op:
        batch_op.drop_index('ix_melduser_id_meldung_id_user')

    with op.batch_alter_table('meldungen', schema=None) as batch_op:
        batch_op.drop_index('ix_meldungen_status_dat_fund_von')
        batch_op.drop_index('ix_meldungen_fo_zuordnung')
        batch_op.drop_index('ix_meldungen_dat_meld')
        batch_op.drop_index('ix_meldungen_dat_fund_von')

    with op.batch_alter_table('fundorte', schema=None) as batch_op:
        batch_op.drop_index('ix_fundorte_amt_pattern', postgresql_ops={'amt': 'varchar_pattern_ops'})

    # ### end Alembic commands ###
