"""convert serial pks to identity

SERIAL is the legacy pre-PG10 spelling; identity columns are the SQL
standard with cleaner sequence ownership. BY DEFAULT (not ALWAYS)
because the demo seed inserts explicit IDs and then resets sequences
via pg_get_serial_sequence(), which resolves identity sequences too.

aemter.ags is a natural key (official AGS municipality codes, always
inserted explicitly) — its never-used sequence is dropped instead.

Revision ID: d2f6b8a4c159
Revises: b6e8a4c2d931
Create Date: 2026-06-10 00:20:00.000000

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "d2f6b8a4c159"
down_revision = "b6e8a4c2d931"
branch_labels = None
depends_on = None

IDENTITY_TABLES = [
    ("beschreibung", "id"),
    ("users", "id"),
    ("fundorte", "id"),
    ("meldungen", "id"),
    ("melduser", "id"),
    ("user_feedback", "id"),
]


def upgrade():
    for table, col in IDENTITY_TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} DROP DEFAULT")
        op.execute(f"DROP SEQUENCE {table}_{col}_seq")
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {col} ADD GENERATED BY DEFAULT AS IDENTITY"
        )
        op.execute(f"""
            SELECT setval(pg_get_serial_sequence('{table}', '{col}'), max({col}))
            FROM {table} HAVING max({col}) IS NOT NULL
        """)

    op.execute("ALTER TABLE aemter ALTER COLUMN ags DROP DEFAULT")
    op.execute("DROP SEQUENCE aemter_ags_seq")


def downgrade():
    for table, col in IDENTITY_TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} DROP IDENTITY")
        op.execute(f"CREATE SEQUENCE {table}_{col}_seq OWNED BY {table}.{col}")
        op.execute(f"""
            SELECT setval('{table}_{col}_seq', max({col}))
            FROM {table} HAVING max({col}) IS NOT NULL
        """)
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {col} "
            f"SET DEFAULT nextval('{table}_{col}_seq')"
        )

    op.execute("CREATE SEQUENCE aemter_ags_seq OWNED BY aemter.ags")
    op.execute("""
        SELECT setval('aemter_ags_seq', max(ags))
        FROM aemter HAVING max(ags) IS NOT NULL
    """)
    op.execute(
        "ALTER TABLE aemter ALTER COLUMN ags SET DEFAULT nextval('aemter_ags_seq')"
    )
