"""Neue Tabellen Tiere und Fundorte

Revision ID: eae6e7acf65c
Revises: 84fa75c73867
Create Date: 2023-04-28 09:44:41.032031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae6e7acf65c'
down_revision = '84fa75c73867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_fundorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plz', sa.Integer(), nullable=False),
    sa.Column('ort', sa.Integer(), nullable=False),
    sa.Column('strasse', sa.String(length=255), nullable=False),
    sa.Column('land', sa.String(length=255), nullable=False),
    sa.Column('kreis', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.VARCHAR(length=255), nullable=False),
    sa.Column('latitude', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'art')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_tiere')
    op.drop_table('tbl_fundorte')
    # ### end Alembic commands ###
