# import the necessary components first
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from app.config import Config


def rendertextmsg(formdata):
    md = formdata.json
    datum = md['dat_fund_von'].split(' ')[1:4]
    md['formdat'] = f"{datum[0]}. {datum[1]}. {datum[2]}"
    return f"""
    Liebe Mantis-Freundin, lieber Mantis-Freund,

    vielen Dank, dass Sie sich am Gottesanbeterinnen-Monitoring beteiligt
    haben. Seit 2016 wurden uns bereits über 2.500 Meldungen aus
    Brandenburg und Berlin gemeldet. Vor allem aus dem Süden
    Brandenburgs. Im Norden wird die Art viel seltener gesichtet. Auch in
    Berlin und Potsdam mehren sich die Funde. Sobald wir Ihre Fundmeldung
    überprüft haben, wird sie in der Verbreitungskarte – hier unter
    Auswertungen – angezeigt. Noch einmal vielen Dank für Ihre Meldung.
    
    Mit freundlichen Grüßen 
    
    Ihr Team vom Mantis-Portal

    Folgende Daten haben wir erhalten:
    ==================================

    Kontakt: { md['user_kontakt'] }
    Ihr Link für neue Meldungen:
    https://gottesanbeterin-gesucht.de/report/{ md['id'] }

    WICHTIGER HINWEIS:

    - Behandeln Sie den Link wie ein Passwort!
    - Publizieren Sie den Link nicht in Foren, Messengern, ...
    
    Latitude:  {md['latitude']}
    Longitude:  {md['longitude']}
    PLZ:  {md['plz']}
    Ort:  {md['ort']}
    Straße:  {md['strasse']}
    Bundesland: {md['land']}
    Kreis: {md['kreis']}
    Funddatum: {md['formdat']}
    """.format(md)


def renderhtmlmsg(formdata):
    md = formdata
    datum = md['dat_fund_von'].split(' ')[1:4]
    md['formdat'] = f"{datum[0]}. {datum[1]}. {datum[2]}"
    return f"""
    <h3>Liebe Mantis-Freundin, lieber Mantis-Freund,</h3>
    
    <p>
    vielen Dank, dass Sie sich am Gottesanbeterinnen-Monitoring beteiligt
    haben. Seit 2016 wurden uns bereits über 2.500 Meldungen aus
    Brandenburg und Berlin gemeldet. Vor allem aus dem Süden
    Brandenburgs. Im Norden wird die Art viel seltener gesichtet. Auch in
    Berlin und Potsdam mehren sich die Funde. Sobald wir Ihre Fundmeldung
    überprüft haben, wird sie in der Verbreitungskarte – hier unter
    Auswertungen – angezeigt. Noch einmal vielen Dank für Ihre Meldung.

    </p>
    <p>
    Mit freundlichen Grüßen
    </p>
    <p>
    Ihr Team vom Mantis-Portal
    </p>
    <hr/>
    <p>Folgende Daten haben wir erhalten:</p>
    <table>
    <tr>    
    <td>Kontakt:</td><td>{ md['user_kontakt'] }</td>
    </tr>
    <tr>    
    <td>Ihr Link für weitere Meldungen</td>
    <td>https://gottesanbeterin-gesucht.de/report/{ md['id'] }</td>
    </tr>
    <tr>    
    <td>Latitude</td>
    <td>{md['latitude']}</td>
    </tr>
    <tr>    
    <td>Longitude</td>
    <td>{md['longitude']}</td>
    </tr>
    <tr>    
    <td>PLZ</td>
    <td>{md['plz']}</td>
    </tr>
    <tr>    
    <td>Ort</td>
    <td>{md['ort']}</td>
    </tr>
    <tr>    
    <td>Straße</td>
    <td>{md['strasse']}</td>
    </tr>
    <tr>    
    <td>Bundesland</td>
    <td>{md['state']}</td>
    </tr>
    <tr>    
    <td>Kreis</td>
    <td>{md['kreis']}</td>
    </tr>
    <tr>    
    <td>Meldedatum</td>
    <td>{md['formdat']}</td>
    </tr>
    <tr>    
     <td>WICHTIGER HINWEIS:</td>
    </tr>    
    <tr>
     <td>
       <ol>
         <li>Behandeln Sie den Link wie ein Passwort</li>
         <li>Publizieren Sie den Link nicht in Foren, Messengern, ...</li>
       </ol>
     <td>
    </tr>    
    </table>
    """.format(md)


def send_email(formdata):
    """ Send a multipart email """

    subject = "Meldebestätigung"
    smtp_server = Config.host
    login = Config.sender_email  # paste your login generated by Mailtrap
    password = Config.sender_pass  # paste your password generated by Mailtrap

    sender_email = Config.sender_email
    receiver_email = formdata.contact.data
    message = MIMEMultipart("alternative")
    message["Subject"] = subject
    message["From"] = sender_email
    message["To"] = receiver_email

    text = rendertextmsg(formdata)
    html = renderhtmlmsg(formdata)

    # convert both parts to MIMEText objects and add them to the MIMEMultipart message
    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")
    message.attach(part1)
    message.attach(part2)
    context = ssl.create_default_context()
    try:
        with smtplib.SMTP(Config.host, Config.port) as server:
            server.starttls(context=context)
            server.login(Config.sender_email, Config.sender_pass)
            server.sendmail(Config.sender_email,
                            receiver_email, message.as_string())
    except Exception as ex:
        raise ex
