# import the necessary components first
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from app.config import Config


def rendertextmsg(formdata):
    md = formdata
    data = {'Kontakt': md.contact.data,
            'link': md.userid,
            'latitude': md.latitude.data,
            'longitude': md.longitude.data,
            'plz': md.zip_code.data,
            'ort': md.city.data,
            'strasse': md.street.data,
            'state': md.state.data,
            'kreis': md.district.data,
            'fundortbeschreibung': md.location_description.data,
            'datum': md.sighting_date.data
            }
    return f"""
    Liebe/r Mantis-Freund*In,

    Vielen Dank, dass Sie sich am Gottesanbeterinnen-Monitoring beteiligt
    haben. Seit 2016 wurden uns bereits über 2.500 Meldungen aus
    Brandenburg und Berlin gemeldet. Vor allem aus dem Süden
    Brandenburgs. Im Norden wird die Art viel seltener gesichtet. Auch in
    Berlin und Potsdam mehren sich die Funde. Sobald wir Ihre Fundmeldung
    überprüft haben, wird sie in der Verbreitungskarte – hier unter
    Auswertungen – angezeigt. Noch einmal vielen Dank für Ihre Meldung.
    
    Mit freundlichen Grüßen 
    
    Ihr Team vom Mantis-Portal

    Folgende Daten haben wir erhalten:
    ==================================

    Kontakt: { data['Kontakt'] }
    Ihr Link für neue Meldungen:  https://gottesanbeterin-gesucht.de/report/{ data['link'] }
    Latitude:  {data['latitude']}
    Longitude:  {data['longitude']}
    PLZ:  {data['plz']}
    Ort:  {data['ort']}
    Straße:  {data['strasse']}
    Bundesland: {data['state']}
    Kreis: {data['kreis']}
    Fundortbeschreibung: {data['fundortbeschreibung']}
    Funddatum: {data['datum']}
    """.format(data)


def renderhtmlmsg(formdata):
    md = formdata
    data = {'Kontakt': md.contact.data,
            'link': md.userid,
            'latitude': md.latitude.data,
            'longitude': md.longitude.data,
            'plz': md.zip_code.data,
            'ort': md.city.data,
            'strasse': md.street.data,
            'state': md.state.data,
            'kreis': md.district.data,
            'fundortbeschreibung': md.location_description.data,
            'datum': md.sighting_date.data
            }

    return f"""
    <h3>Liebe/r Mantis-Freund*In,</h3>
    
    <p>
    Vielen Dank, dass Sie sich am Gottesanbeterinnen-Monitoring beteiligt
    haben. Seit 2016 wurden uns bereits über 2.500 Meldungen aus
    Brandenburg und Berlin gemeldet. Vor allem aus dem Süden
    Brandenburgs. Im Norden wird die Art viel seltener gesichtet. Auch in
    Berlin und Potsdam mehren sich die Funde. Sobald wir Ihre Fundmeldung
    überprüft haben, wird sie in der Verbreitungskarte – hier unter
    Auswertungen – angezeigt. Noch einmal vielen Dank für Ihre Meldung.

    </p>
    <p>
    Mit freundlichen Grüßen
    </p>
    <p>
    Ihr Team vom Mantis-Portal
    </p>
    <hr/>
    <p>Folgende Daten haben wir erhalten:</p>
    <table>
    <tr>    
    <td>Kontakt:</td><td>{ data['Kontakt'] }</td>
    </tr>
    <tr>    
    <td>Ihr Link für weitere Meldungen</td>
    <td>https://gottesanbeterin-gesucht.de/report/{ data['link'] }</td>
    </tr>
    <tr>    
    <td>Latitude</td>
    <td>{data['latitude']}</td>
    </tr>
    <tr>    
    <td>Longitude</td>
    <td>{data['longitude']}</td>
    </tr>
    <tr>    
    <td>PLZ</td>
    <td>{data['plz']}</td>
    </tr>
    <tr>    
    <td>Ort</td>
    <td>{data['ort']}</td>
    </tr>
    <tr>    
    <td>Straße</td>
    <td>{data['strasse']}</td>
    </tr>
    <tr>    
    <td>Bundesland</td>
    <td>{data['state']}</td>
    </tr>
    <tr>    
    <td>Kreis</td>
    <td>{data['kreis']}</td>
    </tr>
    <tr>    
    <td>Beschreibung</td>
    <td>{data['fundortbeschreibung']}</td>
    </tr>
    <tr>    
    <td>Meldedatum</td>
    <td>{data['datum']}</td>
    </tr>
    </table>
    """.format(data)


def send_email(formdata):
    """ Send a multipart email """

    subject = "Meldebestätigung"
    smtp_server = Config.host
    login = Config.sender_email  # paste your login generated by Mailtrap
    password = Config.sender_pass  # paste your password generated by Mailtrap

    sender_email = Config.sender_email
    receiver_email = formdata.contact.data
    message = MIMEMultipart("alternative")
    message["Subject"] = subject
    message["From"] = sender_email
    message["To"] = receiver_email

    text = rendertextmsg(formdata)
    html = renderhtmlmsg(formdata)

    # convert both parts to MIMEText objects and add them to the MIMEMultipart message
    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")
    message.attach(part1)
    message.attach(part2)
    context = ssl.create_default_context()
    try:
        with smtplib.SMTP(Config.host, Config.port) as server:
            server.starttls(context=context)
            server.login(Config.sender_email, Config.sender_pass)
            server.sendmail(Config.sender_email,
                            receiver_email, message.as_string())
    except Exception as ex:
        raise ex
