def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('faq', '/faq')
    config.add_route('impressum', '/impressum')
    config.add_route('about', '/about')
    config.add_route('reportAnIssue', '/reportanissue')
    config.add_route('newItem', '/newitem')
    config.add_route('admin', '/admin')
    config.add_route('mantis', '/mantis')
